# Site settings
author: Jessica Shearwood
title: Why I Chose Software Engineering
header-img: img/home-bg.png
email: letsjesscode@gmail.com
copyright_name: Jessica Shearwood
description: > # this means to ignore newlines until "baseurl:"
   A Fresh Start
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: LetsJessCode
github_username:  LetsJessCode

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
